version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: yamsoft_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - yamsoft_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Web Server for serving static images (nginx)
  nginx:
    image: nginx:alpine
    container_name: yamsoft_nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./images:/usr/share/nginx/html/images:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - yamsoft_network
    depends_on:
      - mysql

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yamsoft_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - yamsoft_network
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local

networks:
  yamsoft_network:
    driver: bridge